apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cockroach-data
  namespace: cockroach
  labels:
    app.kubernetes.io/name: cockroach
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment and set if your cluster has no default StorageClass:
  # storageClassName: standard
