# Replace values before production. Used only on first init (empty data volume).
# See https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-linux
apiVersion: v1
kind: Secret
metadata:
  name: cockroach-init
  namespace: cockroach
  labels:
    app.kubernetes.io/name: cockroach
type: Opaque
stringData:
  cockroach-database: "appdb"
  cockroach-user: "appuser"
  cockroach-password: "changeme-app"
