apiVersion: v1
kind: Service
metadata:
  name: cockroach
  namespace: cockroach
  labels:
    app.kubernetes.io/name: cockroach
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cockroach
  ports:
    - name: grpc
      port: 26257
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
