apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couch-data
  namespace: couchdb
  labels:
    app.kubernetes.io/name: couchdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment and set if your cluster has no default StorageClass:
  # storageClassName: standard
