apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: couchdb
  labels:
    app.kubernetes.io/name: couchdb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: couchdb
  ports:
    - name: http
      port: 5984
      targetPort: http
      protocol: TCP
