apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: mariadb
  labels:
    app.kubernetes.io/name: mariadb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mariadb
  ports:
    - name: mariadb
      port: 3306
      targetPort: mariadb
      protocol: TCP
