apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - name: plaintext
      port: 9092
      targetPort: plaintext
      protocol: TCP
    - name: host
      port: 9094
      targetPort: host
      protocol: TCP
